title: Dargys Ilena Perez Barzaga
description: #
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dargys.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dargys Perez # add your name

# Tracker
# analytics: UA-127898106-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
